### ISSUE TITLE
延时相关的咨询

### ISSUE THREAD

**Issue by maxwell652** [strongercjd/STM32F207VCT6#1]
https://github.com/strongercjd/STM32F207VCT6/blob/f91e0a2055cc4fdf0a2d4b27446acdf5283d4acd/04-Delay/main.c#L77
LOAD是一个24位的寄存器，如果计算出来的延时tick数值大小超过了2^24，是不是延时就不准确了

**Comment by strongercjd** [comment]
是的，延时需要有上限的。几年前我专门写了篇文章讲述了这个问题。https://www.cnblogs.com/Fireflycjd/p/14697900.html
